[package]
name = "commons"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
solana-sdk = { workspace = true }
borsh = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
solana-transaction-status = { workspace = true }