[package]
name = "ticker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
commons = { path = "../commons" }
solana-client = { workspace = true }
solana-sdk = { workspace = true }
tokio-tungstenite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures-util = "0.3"